server:
  port: 8080

spring:
datasource:  //数据库配置
url : jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
username : root
password : 516838682
driverClassName : com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
